"""empty message

Revision ID: 0132aba0ad34
Revises: db9c9aa8030a
Create Date: 2021-07-31 17:40:54.077673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0132aba0ad34'
down_revision = 'db9c9aa8030a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('host', 'host_rating')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('host', sa.Column('host_rating', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
