"""empty message

Revision ID: 37792867391a
Revises: 84dcdd4748ed
Create Date: 2021-08-01 14:38:16.765497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37792867391a'
down_revision = '84dcdd4748ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img', sa.LargeBinary(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('mimetype', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image')
    # ### end Alembic commands ###
