"""empty message

Revision ID: 39452e9cebe4
Revises: 685a03fe8355
Create Date: 2021-07-29 15:25:23.626278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39452e9cebe4'
down_revision = '685a03fe8355'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experience', sa.Column('host_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'experience', 'host', ['host_id'], ['host_id'])
    op.add_column('order', sa.Column('exp_id', sa.Integer(), nullable=True))
    op.add_column('order', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order', 'user', ['user_id'], ['user_id'])
    op.create_foreign_key(None, 'order', 'experience', ['exp_id'], ['exp_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'user_id')
    op.drop_column('order', 'exp_id')
    op.drop_constraint(None, 'experience', type_='foreignkey')
    op.drop_column('experience', 'host_id')
    # ### end Alembic commands ###
