"""empty message

Revision ID: 5797eaa5dac6
Revises: 37792867391a
Create Date: 2021-08-03 10:53:16.293360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5797eaa5dac6'
down_revision = '37792867391a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('exp_id', sa.Integer(), nullable=True))
    op.add_column('image', sa.Column('host_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'image', 'experience', ['exp_id'], ['exp_id'])
    op.create_foreign_key(None, 'image', 'host', ['host_id'], ['host_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'image', type_='foreignkey')
    op.drop_constraint(None, 'image', type_='foreignkey')
    op.drop_column('image', 'host_id')
    op.drop_column('image', 'exp_id')
    # ### end Alembic commands ###
