"""empty message

Revision ID: 685a03fe8355
Revises: 
Create Date: 2021-07-28 19:11:54.461779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '685a03fe8355'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experience',
    sa.Column('exp_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exp_title', sa.String(length=50), nullable=True),
    sa.Column('exp_price', sa.Float(), nullable=True),
    sa.Column('exp_description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('exp_id')
    )
    op.create_table('host',
    sa.Column('host_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('host_full_name', sa.String(), nullable=True),
    sa.Column('host_address', sa.String(), nullable=True),
    sa.Column('host_phone', sa.String(), nullable=True),
    sa.Column('host_introduction', sa.String(length=200), nullable=True),
    sa.Column('host_rating', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('host_id')
    )
    op.create_table('order',
    sa.Column('order_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date_of_order', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=20), nullable=True),
    sa.Column('user_full_name', sa.String(), nullable=True),
    sa.Column('user_address', sa.String(), nullable=True),
    sa.Column('user_phone', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('order')
    op.drop_table('host')
    op.drop_table('experience')
    # ### end Alembic commands ###
