"""empty message

Revision ID: 785210c85a4e
Revises: d6489cb5c2e1
Create Date: 2021-08-11 11:48:16.087857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '785210c85a4e'
down_revision = 'd6489cb5c2e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experience', sa.Column('Total_number_of_guests', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experience', 'Total_number_of_guests')
    # ### end Alembic commands ###
