"""empty message

Revision ID: 84dcdd4748ed
Revises: d5f7abdb3bba
Create Date: 2021-07-31 18:06:39.909142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84dcdd4748ed'
down_revision = 'd5f7abdb3bba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('image_img_key', 'image', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('image_img_key', 'image', ['img'])
    # ### end Alembic commands ###
