"""empty message

Revision ID: c139e0419ea4
Revises: 785210c85a4e
Create Date: 2021-08-11 11:51:29.391270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c139e0419ea4'
down_revision = '785210c85a4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experience', sa.Column('total_number_of_guests', sa.Integer(), nullable=True))
    op.drop_column('experience', 'Total_number_of_guests')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experience', sa.Column('Total_number_of_guests', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('experience', 'total_number_of_guests')
    # ### end Alembic commands ###
