"""empty message

Revision ID: d131321178ad
Revises: c139e0419ea4
Create Date: 2021-08-14 16:45:55.116945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd131321178ad'
down_revision = 'c139e0419ea4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'user_email')
    # ### end Alembic commands ###
