"""empty message

Revision ID: d6489cb5c2e1
Revises: 013fdb122562
Create Date: 2021-08-10 14:15:20.779261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6489cb5c2e1'
down_revision = '013fdb122562'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('host', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'host', 'user', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'host', type_='foreignkey')
    op.drop_column('host', 'user_id')
    # ### end Alembic commands ###
