"""empty message

Revision ID: db9c9aa8030a
Revises: 39452e9cebe4
Create Date: 2021-07-29 20:34:44.376442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db9c9aa8030a'
down_revision = '39452e9cebe4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experience', sa.Column('cuisine', sa.String(length=20), nullable=True))
    op.add_column('experience', sa.Column('dinetime', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experience', 'dinetime')
    op.drop_column('experience', 'cuisine')
    # ### end Alembic commands ###
